import '../app/constants.dart';
import '../models/general.dart';
import '../models/skill.dart';
import '../models/enemy.dart';
import '../models/chapter.dart';
import '../models/event.dart';
import '../models/quest.dart';
import '../models/building.dart';
import '../models/formation.dart';
import '../models/item.dart';

class GameDataService {
  // 全部预设武将
  static List<General> getAllGenerals() => [
    General(
      id: 'guanyu',
      name: '关羽',
      title: '美髯公',
      camp: '蜀',
      quality: Quality.red,
      troopType: TroopType.cavalry,
      level: 1,
      star: 5,
      attributes: GeneralAttributes(
        force: 98,
        intelligence: 75,
        command: 92,
        politics: 64,
        charm: 90,
        speed: 78,
      ),
      skillIds: ['qinglong_yanyue', 'wusheng'],
      bio: '义薄云天，威震华夏。',
    ),
    General(
      id: 'zhangfei',
      name: '张飞',
      title: '燕人张翼德',
      camp: '蜀',
      quality: Quality.orange,
      troopType: TroopType.spear,
      level: 1,
      star: 4,
      attributes: GeneralAttributes(
        force: 96,
        intelligence: 35,
        command: 82,
        politics: 22,
        charm: 50,
        speed: 72,
      ),
      skillIds: ['paoxiao', 'zhangba_she'],
      bio: '燕人张翼德在此！谁敢来决一死战！',
    ),
    General(
      id: 'zhaoyun',
      name: '赵云',
      title: '常山赵子龙',
      camp: '蜀',
      quality: Quality.orange,
      troopType: TroopType.cavalry,
      level: 1,
      star: 4,
      attributes: GeneralAttributes(
        force: 95,
        intelligence: 70,
        command: 88,
        politics: 60,
        charm: 85,
        speed: 90,
      ),
      skillIds: ['longdan', 'qijinchus'],
      bio: '常山赵子龙在此，谁敢一战！',
    ),
    General(
      id: 'zhugeliang',
      name: '诸葛亮',
      title: '卧龙先生',
      camp: '蜀',
      quality: Quality.red,
      troopType: TroopType.strategist,
      level: 1,
      star: 5,
      attributes: GeneralAttributes(
        force: 30,
        intelligence: 100,
        command: 95,
        politics: 95,
        charm: 92,
        speed: 70,
      ),
      skillIds: ['huoji', 'dongfeng'],
      bio: '鞠躬尽瘁，死而后已。',
    ),
    General(
      id: 'liubei',
      name: '刘备',
      title: '仁德之主',
      camp: '蜀',
      quality: Quality.orange,
      troopType: TroopType.infantry,
      level: 1,
      star: 4,
      attributes: GeneralAttributes(
        force: 70,
        intelligence: 75,
        command: 85,
        politics: 90,
        charm: 98,
        speed: 65,
      ),
      skillIds: ['rende', 'taoyuan'],
      bio: '勿以善小而不为，勿以恶小而为之。',
    ),
    General(
      id: 'huangzhong',
      name: '黄忠',
      title: '老当益壮',
      camp: '蜀',
      quality: Quality.purple,
      troopType: TroopType.archer,
      level: 1,
      star: 3,
      attributes: GeneralAttributes(
        force: 92,
        intelligence: 55,
        command: 80,
        politics: 45,
        charm: 65,
        speed: 55,
      ),
      skillIds: ['baiwuchuan'],
      bio: '老夫虽年迈，但宝刀未老！',
    ),
    General(
      id: 'caocao',
      name: '曹操',
      title: '乱世奸雄',
      camp: '魏',
      quality: Quality.red,
      troopType: TroopType.infantry,
      level: 1,
      star: 5,
      attributes: GeneralAttributes(
        force: 78,
        intelligence: 92,
        command: 98,
        politics: 95,
        charm: 80,
        speed: 75,
      ),
      skillIds: ['jianxiong', 'qingshi'],
      bio: '宁教我负天下人，休教天下人负我。',
    ),
    General(
      id: 'lvbu',
      name: '吕布',
      title: '飞将军',
      camp: '群',
      quality: Quality.red,
      troopType: TroopType.cavalry,
      level: 1,
      star: 5,
      attributes: GeneralAttributes(
        force: 100,
        intelligence: 25,
        command: 80,
        politics: 15,
        charm: 30,
        speed: 85,
      ),
      skillIds: ['wushuang', 'fangtian'],
      bio: '人中吕布，马中赤兔。',
    ),
    General(
      id: 'sunce',
      name: '孙策',
      title: '小霸王',
      camp: '吴',
      quality: Quality.orange,
      troopType: TroopType.cavalry,
      level: 1,
      star: 4,
      attributes: GeneralAttributes(
        force: 92,
        intelligence: 65,
        command: 88,
        politics: 60,
        charm: 85,
        speed: 82,
      ),
      skillIds: ['bawang'],
      bio: '江东小霸王，勇冠三军。',
    ),
    General(
      id: 'zhouyu',
      name: '周瑜',
      title: '东吴大都督',
      camp: '吴',
      quality: Quality.orange,
      troopType: TroopType.strategist,
      level: 1,
      star: 4,
      attributes: GeneralAttributes(
        force: 60,
        intelligence: 96,
        command: 92,
        politics: 80,
        charm: 88,
        speed: 72,
      ),
      skillIds: ['huogong', 'zhiyin'],
      bio: '既生瑜，何生亮。',
    ),
    // ===== 紫色武将 =====
    General(
      id: 'dianwei',
      name: '典韦',
      title: '古之恶来',
      camp: '魏',
      quality: Quality.purple,
      troopType: TroopType.infantry,
      star: 3,
      attributes: GeneralAttributes(
        force: 95,
        intelligence: 28,
        command: 70,
        politics: 20,
        charm: 40,
        speed: 60,
      ),
      skillIds: ['luanji'],
      bio: '忠勇无双，死战护主。',
    ),
    General(
      id: 'xuchu',
      name: '许褚',
      title: '虎痴',
      camp: '魏',
      quality: Quality.purple,
      troopType: TroopType.shield,
      star: 3,
      attributes: GeneralAttributes(
        force: 93,
        intelligence: 25,
        command: 68,
        politics: 18,
        charm: 35,
        speed: 55,
      ),
      skillIds: ['fangyu'],
      bio: '裸衣斗马超，虎痴之名威震天下。',
    ),
    General(
      id: 'taishici',
      name: '太史慈',
      title: '信义笃烈',
      camp: '吴',
      quality: Quality.purple,
      troopType: TroopType.archer,
      star: 3,
      attributes: GeneralAttributes(
        force: 90,
        intelligence: 55,
        command: 78,
        politics: 42,
        charm: 68,
        speed: 72,
      ),
      skillIds: ['baiwuchuan'],
      bio: '大丈夫生于乱世，当带三尺剑立不世之功。',
    ),
    General(
      id: 'ganning',
      name: '甘宁',
      title: '锦帆贼',
      camp: '吴',
      quality: Quality.purple,
      troopType: TroopType.infantry,
      star: 3,
      attributes: GeneralAttributes(
        force: 88,
        intelligence: 50,
        command: 75,
        politics: 30,
        charm: 55,
        speed: 78,
      ),
      skillIds: ['luanji'],
      bio: '百骑劫曹营，勇冠三军。',
    ),
    General(
      id: 'zhangliao',
      name: '张辽',
      title: '威震逍遥津',
      camp: '魏',
      quality: Quality.purple,
      troopType: TroopType.cavalry,
      star: 3,
      attributes: GeneralAttributes(
        force: 89,
        intelligence: 72,
        command: 88,
        politics: 48,
        charm: 62,
        speed: 80,
      ),
      skillIds: ['luanji'],
      bio: '张辽在此，吴儿破胆！',
    ),
    // ===== 蓝色武将 =====
    General(
      id: 'liaohua',
      name: '廖化',
      title: '蜀汉先锋',
      camp: '蜀',
      quality: Quality.blue,
      troopType: TroopType.infantry,
      star: 2,
      attributes: GeneralAttributes(
        force: 70,
        intelligence: 55,
        command: 65,
        politics: 50,
        charm: 48,
        speed: 60,
      ),
      skillIds: ['luanji'],
      bio: '蜀中无大将，廖化作先锋。',
    ),
    General(
      id: 'wangping',
      name: '王平',
      title: '平安三军',
      camp: '蜀',
      quality: Quality.blue,
      troopType: TroopType.shield,
      star: 2,
      attributes: GeneralAttributes(
        force: 68,
        intelligence: 62,
        command: 72,
        politics: 45,
        charm: 42,
        speed: 55,
      ),
      skillIds: ['fangyu'],
      bio: '街亭之战，唯王平一军不乱。',
    ),
    General(
      id: 'caoxiu',
      name: '曹休',
      title: '千里驹',
      camp: '魏',
      quality: Quality.blue,
      troopType: TroopType.cavalry,
      star: 2,
      attributes: GeneralAttributes(
        force: 75,
        intelligence: 60,
        command: 70,
        politics: 45,
        charm: 50,
        speed: 72,
      ),
      skillIds: ['luanji'],
      bio: '曹氏千里驹，勇而有谋。',
    ),
    General(
      id: 'huanggai',
      name: '黄盖',
      title: '苦肉计',
      camp: '吴',
      quality: Quality.blue,
      troopType: TroopType.infantry,
      star: 2,
      attributes: GeneralAttributes(
        force: 72,
        intelligence: 65,
        command: 68,
        politics: 48,
        charm: 55,
        speed: 58,
      ),
      skillIds: ['fangyu'],
      bio: '赤壁之战，黄盖献苦肉计。',
    ),
    General(
      id: 'chenggong',
      name: '陈宫',
      title: '刚直壮烈',
      camp: '群',
      quality: Quality.blue,
      troopType: TroopType.strategist,
      star: 2,
      attributes: GeneralAttributes(
        force: 35,
        intelligence: 82,
        command: 60,
        politics: 78,
        charm: 55,
        speed: 50,
      ),
      skillIds: ['luanji'],
      bio: '陈宫智谋不输郭嘉，可惜所托非人。',
    ),
    // ===== 绿色武将 =====
    General(
      id: 'guanxing',
      name: '关兴',
      title: '关公之子',
      camp: '蜀',
      quality: Quality.green,
      troopType: TroopType.cavalry,
      star: 1,
      attributes: GeneralAttributes(
        force: 65,
        intelligence: 45,
        command: 55,
        politics: 35,
        charm: 50,
        speed: 62,
      ),
      skillIds: [],
      bio: '关公之子，继承父亲遗志。',
    ),
    General(
      id: 'zhangbao',
      name: '张苞',
      title: '翼德之子',
      camp: '蜀',
      quality: Quality.green,
      troopType: TroopType.spear,
      star: 1,
      attributes: GeneralAttributes(
        force: 68,
        intelligence: 35,
        command: 50,
        politics: 25,
        charm: 40,
        speed: 58,
      ),
      skillIds: [],
      bio: '张飞之子，勇猛善战。',
    ),
    General(
      id: 'caozhang',
      name: '曹彰',
      title: '黄须儿',
      camp: '魏',
      quality: Quality.green,
      troopType: TroopType.cavalry,
      star: 1,
      attributes: GeneralAttributes(
        force: 72,
        intelligence: 30,
        command: 52,
        politics: 22,
        charm: 38,
        speed: 65,
      ),
      skillIds: [],
      bio: '曹操之子，臂力过人，善射。',
    ),
    General(
      id: 'sunquan_soldier',
      name: '周泰',
      title: '铁壁将军',
      camp: '吴',
      quality: Quality.green,
      troopType: TroopType.shield,
      star: 1,
      attributes: GeneralAttributes(
        force: 60,
        intelligence: 38,
        command: 58,
        politics: 30,
        charm: 42,
        speed: 50,
      ),
      skillIds: [],
      bio: '身被十二创，护卫孙权脱险。',
    ),
    // ===== 白色武将 =====
    General(
      id: 'militia_leader',
      name: '乡勇头领',
      title: '义勇之士',
      camp: '群',
      quality: Quality.white,
      troopType: TroopType.infantry,
      star: 1,
      attributes: GeneralAttributes(
        force: 45,
        intelligence: 30,
        command: 40,
        politics: 25,
        charm: 30,
        speed: 40,
      ),
      skillIds: [],
      bio: '乱世之中挺身而出的乡勇头领。',
    ),
    General(
      id: 'wandering_scholar',
      name: '游学书生',
      title: '行走四方',
      camp: '群',
      quality: Quality.white,
      troopType: TroopType.strategist,
      star: 1,
      attributes: GeneralAttributes(
        force: 20,
        intelligence: 55,
        command: 30,
        politics: 50,
        charm: 40,
        speed: 35,
      ),
      skillIds: [],
      bio: '四方游学的书生，略通兵法。',
    ),
    General(
      id: 'retired_soldier',
      name: '退伍老兵',
      title: '久经沙场',
      camp: '群',
      quality: Quality.white,
      troopType: TroopType.spear,
      star: 1,
      attributes: GeneralAttributes(
        force: 50,
        intelligence: 28,
        command: 45,
        politics: 20,
        charm: 25,
        speed: 35,
      ),
      skillIds: [],
      bio: '退伍老兵，虽年迈但经验丰富。',
    ),
    General(
      id: 'mountain_hunter',
      name: '山中猎户',
      title: '神射手',
      camp: '群',
      quality: Quality.white,
      troopType: TroopType.archer,
      star: 1,
      attributes: GeneralAttributes(
        force: 48,
        intelligence: 25,
        command: 30,
        politics: 15,
        charm: 22,
        speed: 52,
      ),
      skillIds: [],
      bio: '山中猎户出身，箭术精湛。',
    ),
  ];

  // 全部技能
  static List<Skill> getAllSkills() => [
    Skill(
      id: 'qinglong_yanyue',
      name: '青龙偃月斩',
      description: '对敌方全体造成210%武力伤害，30%概率眩晕',
      type: SkillType.active,
      targetType: TargetType.allEnemy,
      costRage: 50,
      cooldown: 2,
      scaleAttribute: 'force',
      multiplier: 2.1,
      effects: [
        SkillEffect(type: 'damage'),
        SkillEffect(type: 'stun', chance: 0.3, duration: 1),
      ],
    ),
    Skill(
      id: 'wusheng',
      name: '武圣',
      description: '被动：攻击力提升15%',
      type: SkillType.passive,
      scaleAttribute: 'force',
      multiplier: 1.15,
    ),
    Skill(
      id: 'paoxiao',
      name: '咆哮',
      description: '对敌方前排造成180%武力伤害，降低防御20%',
      type: SkillType.active,
      targetType: TargetType.frontRow,
      costRage: 40,
      cooldown: 2,
      scaleAttribute: 'force',
      multiplier: 1.8,
      effects: [
        SkillEffect(type: 'damage'),
        SkillEffect(type: 'armorBreak', chance: 0.8, duration: 2, value: 0.2),
      ],
    ),
    Skill(
      id: 'zhangba_she',
      name: '丈八蛇矛',
      description: '被动：攻击时15%概率额外伤害',
      type: SkillType.passive,
      scaleAttribute: 'force',
      multiplier: 1.15,
    ),
    Skill(
      id: 'longdan',
      name: '龙胆',
      description: '被动：生命低于40%时闪避率提升25%',
      type: SkillType.passive,
      scaleAttribute: 'speed',
      multiplier: 1.25,
    ),
    Skill(
      id: 'qijinchus',
      name: '七进七出',
      description: '对随机敌方造成3次150%武力伤害',
      type: SkillType.active,
      targetType: TargetType.singleEnemy,
      costRage: 55,
      cooldown: 3,
      scaleAttribute: 'force',
      multiplier: 1.5,
    ),
    Skill(
      id: 'huoji',
      name: '火计',
      description: '对敌方全体造成160%智力伤害，附加灼烧2回合',
      type: SkillType.active,
      targetType: TargetType.allEnemy,
      costRage: 60,
      cooldown: 3,
      scaleAttribute: 'intelligence',
      multiplier: 1.6,
      effects: [
        SkillEffect(type: 'damage'),
        SkillEffect(type: 'burn', chance: 0.8, duration: 2, value: 0.1),
      ],
    ),
    Skill(
      id: 'dongfeng',
      name: '借东风',
      description: '提升我方全体速度20%，持续3回合',
      type: SkillType.active,
      targetType: TargetType.allAlly,
      costRage: 50,
      cooldown: 4,
      scaleAttribute: 'intelligence',
      multiplier: 1.0,
      effects: [SkillEffect(type: 'buff', duration: 3, value: 0.2)],
    ),
    Skill(
      id: 'rende',
      name: '仁德',
      description: '恢复我方全体生命，并提升民心',
      type: SkillType.active,
      targetType: TargetType.allAlly,
      costRage: 50,
      cooldown: 3,
      scaleAttribute: 'charm',
      multiplier: 1.0,
      effects: [SkillEffect(type: 'heal', value: 0.3)],
    ),
    Skill(
      id: 'taoyuan',
      name: '桃园结义',
      description: '合击：与关羽张飞同时上阵可触发',
      type: SkillType.combo,
      targetType: TargetType.allEnemy,
      costRage: 80,
      cooldown: 5,
      scaleAttribute: 'force',
      multiplier: 2.5,
      effects: [
        SkillEffect(type: 'damage'),
        SkillEffect(type: 'heal', value: 0.2),
      ],
    ),
    Skill(
      id: 'baiwuchuan',
      name: '百步穿杨',
      description: '对单体造成250%武力伤害',
      type: SkillType.active,
      targetType: TargetType.singleEnemy,
      costRage: 45,
      cooldown: 2,
      scaleAttribute: 'force',
      multiplier: 2.5,
    ),
    Skill(
      id: 'jianxiong',
      name: '奸雄',
      description: '被动：受到伤害时恢复10%怒气',
      type: SkillType.passive,
      scaleAttribute: 'intelligence',
      multiplier: 1.0,
    ),
    Skill(
      id: 'qingshi',
      name: '青史留名',
      description: '提升我方全体攻击10%',
      type: SkillType.active,
      targetType: TargetType.allAlly,
      costRage: 45,
      cooldown: 3,
      scaleAttribute: 'command',
      multiplier: 1.0,
      effects: [SkillEffect(type: 'buff', duration: 3, value: 0.1)],
    ),
    Skill(
      id: 'wushuang',
      name: '无双',
      description: '对敌方全体造成280%武力伤害',
      type: SkillType.active,
      targetType: TargetType.allEnemy,
      costRage: 60,
      cooldown: 3,
      scaleAttribute: 'force',
      multiplier: 2.8,
    ),
    Skill(
      id: 'fangtian',
      name: '方天画戟',
      description: '被动：攻击附带10%吸血',
      type: SkillType.passive,
      scaleAttribute: 'force',
      multiplier: 1.1,
    ),
    Skill(
      id: 'bawang',
      name: '霸王之击',
      description: '对单体造成220%武力伤害',
      type: SkillType.active,
      targetType: TargetType.singleEnemy,
      costRage: 40,
      cooldown: 2,
      scaleAttribute: 'force',
      multiplier: 2.2,
    ),
    Skill(
      id: 'huogong',
      name: '火攻',
      description: '对敌方全体造成140%智力伤害',
      type: SkillType.active,
      targetType: TargetType.allEnemy,
      costRage: 50,
      cooldown: 2,
      scaleAttribute: 'intelligence',
      multiplier: 1.4,
    ),
    Skill(
      id: 'zhiyin',
      name: '知音',
      description: '被动：战斗开始全体怒气+15',
      type: SkillType.passive,
      scaleAttribute: 'charm',
      multiplier: 1.0,
    ),
    // 通用技能
    Skill(
      id: 'luanji',
      name: '乱击',
      description: '对单体造成150%武力伤害',
      type: SkillType.active,
      targetType: TargetType.singleEnemy,
      costRage: 30,
      cooldown: 1,
      scaleAttribute: 'force',
      multiplier: 1.5,
    ),
    Skill(
      id: 'fangyu',
      name: '坚守',
      description: '本回合受到伤害降低50%',
      type: SkillType.active,
      targetType: TargetType.self,
      costRage: 20,
      cooldown: 2,
      effects: [SkillEffect(type: 'shield', duration: 1, value: 0.5)],
    ),
  ];

  // 全部敌人
  static List<Enemy> getAllEnemies() => [
    Enemy(
      id: 'yt_bandit',
      name: '黄巾兵甲',
      level: 1,
      troopType: TroopType.infantry,
      hp: 600,
      maxHp: 600,
      force: 30,
      intelligence: 15,
      command: 20,
      speed: 25,
    ),
    Enemy(
      id: 'yt_bandit2',
      name: '黄巾兵乙',
      level: 1,
      troopType: TroopType.infantry,
      hp: 500,
      maxHp: 500,
      force: 28,
      intelligence: 12,
      command: 18,
      speed: 22,
    ),
    Enemy(
      id: 'yt_archer',
      name: '黄巾弓手',
      level: 2,
      troopType: TroopType.archer,
      hp: 450,
      maxHp: 450,
      force: 35,
      intelligence: 20,
      command: 22,
      speed: 30,
    ),
    Enemy(
      id: 'yt_leader',
      name: '黄巾渠帅',
      level: 3,
      troopType: TroopType.infantry,
      hp: 1200,
      maxHp: 1200,
      force: 45,
      intelligence: 30,
      command: 40,
      speed: 35,
      skillIds: ['luanji'],
      isBoss: true,
    ),
    Enemy(
      id: 'yt_elite',
      name: '黄巾力士',
      level: 2,
      troopType: TroopType.shield,
      hp: 800,
      maxHp: 800,
      force: 38,
      intelligence: 18,
      command: 35,
      speed: 20,
    ),
    Enemy(
      id: 'dz_soldier',
      name: '董卓铁骑',
      level: 4,
      troopType: TroopType.cavalry,
      hp: 900,
      maxHp: 900,
      force: 55,
      intelligence: 25,
      command: 45,
      speed: 50,
    ),
    Enemy(
      id: 'dz_guard',
      name: '西凉铁卫',
      level: 5,
      troopType: TroopType.shield,
      hp: 1100,
      maxHp: 1100,
      force: 50,
      intelligence: 30,
      command: 55,
      speed: 35,
    ),
    Enemy(
      id: 'lvbu_boss',
      name: '吕布',
      level: 8,
      troopType: TroopType.cavalry,
      hp: 3000,
      maxHp: 3000,
      force: 100,
      intelligence: 25,
      command: 80,
      speed: 85,
      skillIds: ['wushuang', 'fangtian'],
      isBoss: true,
    ),
    Enemy(
      id: 'zj_soldier',
      name: '张角信徒',
      level: 3,
      troopType: TroopType.strategist,
      hp: 550,
      maxHp: 550,
      force: 20,
      intelligence: 50,
      command: 25,
      speed: 40,
    ),
    Enemy(
      id: 'zj_boss',
      name: '张梁',
      level: 5,
      troopType: TroopType.infantry,
      hp: 1800,
      maxHp: 1800,
      force: 60,
      intelligence: 40,
      command: 55,
      speed: 45,
      skillIds: ['luanji'],
      isBoss: true,
    ),
    // 第三章敌人
    Enemy(
      id: 'yuan_shao_soldier',
      name: '袁绍弓箭手',
      level: 6,
      troopType: TroopType.archer,
      hp: 700,
      maxHp: 700,
      force: 58,
      intelligence: 35,
      command: 40,
      speed: 48,
    ),
    Enemy(
      id: 'yuan_shao_cavalry',
      name: '袁绍铁骑',
      level: 7,
      troopType: TroopType.cavalry,
      hp: 1000,
      maxHp: 1000,
      force: 70,
      intelligence: 30,
      command: 55,
      speed: 60,
    ),
    Enemy(
      id: 'yuan_shu_guard',
      name: '袁术盾卫',
      level: 6,
      troopType: TroopType.shield,
      hp: 1200,
      maxHp: 1200,
      force: 45,
      intelligence: 28,
      command: 65,
      speed: 30,
    ),
    Enemy(
      id: 'yanliang',
      name: '颜良',
      level: 9,
      troopType: TroopType.infantry,
      hp: 2200,
      maxHp: 2200,
      force: 88,
      intelligence: 35,
      command: 72,
      speed: 55,
      skillIds: ['luanji'],
      isBoss: true,
    ),
    Enemy(
      id: 'wenchou',
      name: '文丑',
      level: 9,
      troopType: TroopType.cavalry,
      hp: 2000,
      maxHp: 2000,
      force: 85,
      intelligence: 30,
      command: 68,
      speed: 65,
      skillIds: ['luanji'],
      isBoss: true,
    ),
    // 第四章敌人
    Enemy(
      id: 'cao_soldier',
      name: '曹军步兵',
      level: 8,
      troopType: TroopType.infantry,
      hp: 900,
      maxHp: 900,
      force: 65,
      intelligence: 40,
      command: 55,
      speed: 45,
    ),
    Enemy(
      id: 'cao_archer',
      name: '曹军弓手',
      level: 8,
      troopType: TroopType.archer,
      hp: 750,
      maxHp: 750,
      force: 62,
      intelligence: 42,
      command: 48,
      speed: 50,
    ),
    Enemy(
      id: 'xiahou_dun',
      name: '夏侯惇',
      level: 11,
      troopType: TroopType.infantry,
      hp: 2500,
      maxHp: 2500,
      force: 92,
      intelligence: 50,
      command: 80,
      speed: 60,
      skillIds: ['luanji'],
      isBoss: true,
    ),
    // 第五章敌人
    Enemy(
      id: 'elite_guard',
      name: '精锐禁卫',
      level: 10,
      troopType: TroopType.shield,
      hp: 1500,
      maxHp: 1500,
      force: 70,
      intelligence: 45,
      command: 75,
      speed: 40,
    ),
    Enemy(
      id: 'elite_mage',
      name: '宫廷术士',
      level: 10,
      troopType: TroopType.strategist,
      hp: 800,
      maxHp: 800,
      force: 30,
      intelligence: 85,
      command: 50,
      speed: 55,
      skillIds: ['huogong'],
    ),
    Enemy(
      id: 'final_boss',
      name: '帝王守卫',
      level: 15,
      troopType: TroopType.infantry,
      hp: 5000,
      maxHp: 5000,
      force: 100,
      intelligence: 80,
      command: 95,
      speed: 70,
      skillIds: ['wushuang', 'fangyu'],
      isBoss: true,
    ),
  ];

  // 章节数据
  static List<Chapter> getAllChapters() => [
    Chapter(
      id: 1,
      name: '第一章：黄巾乱起',
      description:
          '中平元年，张角以「苍天已死，黄天当立」为口号，发动黄巾起义。数十万教众蜂拥而起，烽烟遍及各州郡。你受命守卫平原城，在这乱世中迈出第一步。',
      isUnlocked: true,
      stages: [
        Stage(
          id: '1-1',
          name: '流民求援',
          type: StageType.story,
          recommendedLevel: 1,
          enemyIds: [],
          rewards: QuestReward(coin: 500, grain: 300, exp: 100),
          storyContent:
              '【平原城外·黄昏】\n\n残阳如血，远处地平线上升起数道浓烟。\n\n城门守卫匆匆来报：「大人！城外来了数百流民，皆是衣衫褴褛、扶老携幼，说是从广宗逃难而来。」\n\n你登上城头望去，只见黑压压一片人群跪在护城河外。领头老者声泪俱下：\n\n「大人开恩！黄巾贼人攻入广宗，见人便杀、见屋便烧。我等拼死逃出，已是走投无路……」\n\n身旁幕僚低声道：「大人，城中粮草本就不多。且黄巾势大，若收留流民，恐贼军尾随而至。但若不开门……民心恐有动摇。」',
          storyEnding: '你决定妥善处理流民事宜。乱世之中，每一个抉择都关乎生死存亡。\n\n黄巾之乱的序幕，就此拉开。',
        ),
        Stage(
          id: '1-2',
          name: '黄巾伏击',
          type: StageType.normal,
          recommendedLevel: 1,
          enemyIds: ['yt_bandit', 'yt_bandit2'],
          rewards: QuestReward(coin: 800, grain: 500, exp: 200),
        ),
        Stage(
          id: '1-3',
          name: '守卫村庄',
          type: StageType.normal,
          recommendedLevel: 2,
          enemyIds: ['yt_bandit', 'yt_archer', 'yt_bandit2'],
          rewards: QuestReward(coin: 1000, grain: 600, exp: 300),
        ),
        Stage(
          id: '1-4',
          name: '张角妖术',
          type: StageType.elite,
          recommendedLevel: 3,
          enemyIds: ['zj_soldier', 'zj_soldier', 'yt_elite'],
          rewards: QuestReward(coin: 1500, grain: 800, exp: 500),
        ),
        Stage(
          id: '1-5',
          name: '平定县城',
          type: StageType.boss,
          recommendedLevel: 3,
          enemyIds: ['yt_leader', 'yt_bandit', 'yt_archer'],
          rewards: QuestReward(
            coin: 3000,
            grain: 2000,
            exp: 800,
            reputation: 20,
          ),
        ),
      ],
    ),
    Chapter(
      id: 2,
      name: '第二章：董卓入京',
      description:
          '灵帝驾崩，大将军何进欲诛宦官，密召凉州牧董卓入京。董卓趁乱把持朝政，废立天子，祸乱朝纲。天下群雄愤而起兵，会盟讨伐暴臣。',
      stages: [
        Stage(
          id: '2-1',
          name: '洛阳密信',
          type: StageType.story,
          recommendedLevel: 5,
          enemyIds: [],
          rewards: QuestReward(coin: 1000, exp: 300),
          storyContent:
              '【平原府邸·深夜】\n\n一阵急促的敲门声将你从睡梦中惊醒。\n\n亲卫呈上一封以蜡封缄的密信，信封上赫然写着「讨逆联盟」四字。\n\n你拆开信笺，借着烛光细读：\n\n「董卓擅权，废少帝立献帝，自封相国。其狼子野心，人神共愤。今袁绍、曹操等十八路诸侯会盟酸枣，共商讨董大计。望将军整备兵马，共赴国难。」\n\n「——渤海太守袁绍」\n\n幕僚连夜赶来，面色凝重：「大人，董卓麾下铁骑二十万，又有吕布这等猛将。此去凶多吉少，但若坐视不理，恐失天下人心。」\n\n你望向窗外漆黑的夜空，洛阳方向隐约可见火光冲天。',
          storyEnding: '你决定响应联盟号召，整军出发。\n\n讨董之战，就此开始。虎牢关前，一场惊天动地的大战即将上演。',
        ),
        Stage(
          id: '2-2',
          name: '虎牢关前哨',
          type: StageType.normal,
          recommendedLevel: 5,
          enemyIds: ['dz_soldier', 'dz_soldier'],
          rewards: QuestReward(coin: 1500, grain: 1000, exp: 500),
        ),
        Stage(
          id: '2-3',
          name: '诸侯会盟',
          type: StageType.story,
          recommendedLevel: 6,
          enemyIds: [],
          rewards: QuestReward(coin: 2000, reputation: 10),
          storyContent:
              '【酸枣·诸侯大营】\n\n十八路诸侯齐聚，旌旗遮天蔽日。\n\n袁绍身披金甲，立于高台之上，朗声道：\n\n「汉室不幸，皇纲失统，贼臣董卓乘衅纵害，祸加至尊，虐流百姓！今各兴义兵，共赴国难！」\n\n台下群情激愤，各路诸侯纷纷拔剑立誓。\n\n然而你注意到，人群中有些人眼神闪烁——袁术左顾右盼，似乎心怀鬼胎；曹操冷眼旁观，嘴角带着一丝意味深长的笑意。\n\n盟军能否齐心合力？你心中隐隐有些不安。\n\n帐外忽然传来喧哗：「报——！虎牢关守将华雄出阵挑战，已斩杀我方数员将领！」',
          storyEnding: '诸侯联盟虽有嫌隙，但讨董的决心暂时将众人凝聚在一起。\n\n虎牢关大战在即，谁能一战成名？',
        ),
        Stage(
          id: '2-4',
          name: '吕布挑战',
          type: StageType.boss,
          recommendedLevel: 7,
          enemyIds: ['lvbu_boss', 'dz_guard'],
          rewards: QuestReward(
            coin: 5000,
            grain: 3000,
            exp: 1500,
            reputation: 30,
          ),
        ),
        Stage(
          id: '2-5',
          name: '洛阳大火',
          type: StageType.elite,
          recommendedLevel: 8,
          enemyIds: ['dz_soldier', 'dz_guard', 'dz_soldier'],
          rewards: QuestReward(coin: 3000, grain: 2000, exp: 1000),
        ),
      ],
    ),
    Chapter(
      id: 3,
      name: '第三章：群雄割据',
      description:
          '董卓伏诛后，诸侯各怀异志，联盟瓦解。袁绍据河北、曹操占中原、孙策定江东……群雄逐鹿中原，你必须在乱世中找到自己的立足之地。',
      stages: [
        Stage(
          id: '3-1',
          name: '徐州求援',
          type: StageType.story,
          recommendedLevel: 6,
          enemyIds: [],
          rewards: QuestReward(coin: 1500, exp: 400),
          storyContent:
              '【府邸·议事厅】\n\n快马送来十万火急的战报。\n\n徐州牧陶谦遣使求援，使者跪伏在地，泣不成声：\n\n「曹操以报父仇为名，率大军攻打徐州。曹军所过之处，寸草不留、尸横遍野。我家主公已年过六旬，实在无力抵抗，特求将军出兵相救！」\n\n你展开地图，只见徐州四周已被曹军包围，形势岌岌可危。\n\n谋士分析道：「曹操兵强马壮，正面交锋恐难取胜。但若坐视徐州陷落，曹操势力将更加庞大，于我等极为不利。」\n\n「且陶谦仁厚，在徐州颇有民心。若施以援手，可结下善缘。但若出兵……北方袁绍虎视眈眈，不得不防。」',
          storyEnding: '徐州之战，牵动天下格局。你做出了自己的选择。\n\n乱世之中，没有永远的盟友，也没有永远的敌人。',
        ),
        Stage(
          id: '3-2',
          name: '袁绍前锋',
          type: StageType.normal,
          recommendedLevel: 6,
          enemyIds: ['yuan_shao_soldier', 'yuan_shao_soldier'],
          rewards: QuestReward(coin: 2000, grain: 1200, exp: 600),
        ),
        Stage(
          id: '3-3',
          name: '袁术称帝',
          type: StageType.normal,
          recommendedLevel: 7,
          enemyIds: ['yuan_shu_guard', 'yuan_shao_cavalry'],
          rewards: QuestReward(coin: 2500, grain: 1500, exp: 800),
        ),
        Stage(
          id: '3-4',
          name: '官渡前哨',
          type: StageType.elite,
          recommendedLevel: 8,
          enemyIds: [
            'yuan_shao_cavalry',
            'yuan_shao_soldier',
            'yuan_shu_guard',
          ],
          rewards: QuestReward(coin: 3000, grain: 2000, exp: 1000),
        ),
        Stage(
          id: '3-5',
          name: '斩颜良',
          type: StageType.boss,
          recommendedLevel: 9,
          enemyIds: ['yanliang', 'yuan_shao_soldier'],
          rewards: QuestReward(
            coin: 5000,
            grain: 3000,
            exp: 1500,
            reputation: 25,
          ),
        ),
        Stage(
          id: '3-6',
          name: '诛文丑',
          type: StageType.boss,
          recommendedLevel: 9,
          enemyIds: ['wenchou', 'yuan_shao_cavalry'],
          rewards: QuestReward(
            coin: 5000,
            grain: 3000,
            exp: 1500,
            reputation: 25,
          ),
        ),
      ],
    ),
    Chapter(
      id: 4,
      name: '第四章：赤壁之战',
      description:
          '曹操一统北方，挥师南下，号称百万大军压境。江东孙权与刘备联军，决意于赤壁与曹操一决雌雄。这一战，将决定天下三分的格局。',
      stages: [
        Stage(
          id: '4-1',
          name: '连环计',
          type: StageType.story,
          recommendedLevel: 8,
          enemyIds: [],
          rewards: QuestReward(coin: 2000, exp: 500),
          storyContent:
              '【柴桑·周瑜水寨】\n\n江风猎猎，战船密布。\n\n周瑜指着对岸曹操连绵数十里的水寨，冷笑道：\n\n「曹操虽号称八十万大军，但多是北方旱鸭子，不识水性。若能将战船以铁索连环，使其不能散开……一把火，便可尽数烧毁！」\n\n诸葛亮摇着羽扇，补充道：「但曹操生性多疑，需有人献计，使他心甘情愿将船只连在一起。」\n\n帐中诸将面面相觑。这时，老将黄盖挺身而出：\n\n「老夫愿施苦肉计！当众受责，假意投降曹操，趁机献连环之计！」\n\n周瑜与诸葛亮对视一眼，缓缓点头。一场精密的连环计，就此展开……',
          storyEnding: '苦肉计、连环计，一环扣一环。\n\n万事俱备，只欠东风。赤壁之战的序幕即将拉开。',
        ),
        Stage(
          id: '4-2',
          name: '草船借箭',
          type: StageType.normal,
          recommendedLevel: 8,
          enemyIds: ['cao_soldier', 'cao_archer', 'cao_soldier'],
          rewards: QuestReward(coin: 3000, grain: 2000, exp: 800),
        ),
        Stage(
          id: '4-3',
          name: '借东风',
          type: StageType.story,
          recommendedLevel: 9,
          enemyIds: [],
          rewards: QuestReward(coin: 2500, reputation: 15),
          storyContent:
              '【赤壁·江面】\n\n万事俱备，但周瑜却愁眉不展。\n\n「火攻之策已定，但如今正值隆冬，江上尽吹西北风。若此时放火，火势反而会烧向我军！」\n\n诸葛亮微微一笑，从袖中取出一张纸条：\n\n「亮于南屏山设七星坛，三日后辰时，必有东南风起。都督只管安排火攻诸事。」\n\n周瑜将信将疑。\n\n三日后，天刚蒙蒙亮——\n\n江面上忽然风旗猎猎作响，风向竟真的转为东南！\n\n将士们欢呼雀跃。诸葛亮于坛上遥望曹营方向，喃喃自语：\n\n「天命在我，汉室可兴。」\n\n周瑜闻讯，立即下令：「全军出击！」',
          storyEnding: '东风已至，火攻就绪。\n\n赤壁之战，即将改写天下格局！',
        ),
        Stage(
          id: '4-4',
          name: '火烧赤壁',
          type: StageType.elite,
          recommendedLevel: 10,
          enemyIds: ['cao_soldier', 'cao_archer', 'cao_soldier', 'cao_archer'],
          rewards: QuestReward(coin: 5000, grain: 3000, exp: 1500),
        ),
        Stage(
          id: '4-5',
          name: '夏侯惇截击',
          type: StageType.boss,
          recommendedLevel: 11,
          enemyIds: ['xiahou_dun', 'cao_soldier', 'cao_archer'],
          rewards: QuestReward(
            coin: 8000,
            grain: 5000,
            exp: 2000,
            reputation: 30,
          ),
        ),
      ],
    ),
    Chapter(
      id: 5,
      name: '第五章：问鼎天下',
      description:
          '赤壁之战后，天下三分。魏蜀吴三足鼎立，但和平只是暂时的。你将做出最终的抉择——是匡扶汉室，还是开创属于自己的新朝？最终之战，一触即发。',
      stages: [
        Stage(
          id: '5-1',
          name: '三分归一',
          type: StageType.story,
          recommendedLevel: 10,
          enemyIds: [],
          rewards: QuestReward(coin: 3000, exp: 800),
          storyContent:
              '【王宫·大殿】\n\n赤壁之战已过去数年，天下三分的格局逐渐稳固。\n\n你端坐于大殿之上，群臣环列两侧。\n\n谋士上前奏道：「主公，如今魏蜀吴三足鼎立，各方都在休养生息、积蓄力量。但天下未定，终有一战。」\n\n武将抱拳道：「主公！我军兵精粮足，将士用命。此时不取天下，更待何时？」\n\n文臣则持不同意见：「连年征战，百姓疲敝。不如先安内政、发展农桑，待时机成熟再图大业。」\n\n你站起身，走到窗前。远方是繁华的都城，百姓安居乐业。\n\n但你知道，乱世终要有一个终结。\n\n是兴复汉室、还政于天子？是开创新朝、建立不世之功？还是……\n\n这个决定，将影响千秋万代。',
          storyEnding: '天下大势，分久必合。\n\n你做出了最终的抉择，踏上了问鼎天下的征途。这一战，将决定历史的走向。',
        ),
        Stage(
          id: '5-2',
          name: '北伐中原',
          type: StageType.normal,
          recommendedLevel: 10,
          enemyIds: ['elite_guard', 'elite_mage'],
          rewards: QuestReward(coin: 4000, grain: 3000, exp: 1200),
        ),
        Stage(
          id: '5-3',
          name: '决战许昌',
          type: StageType.elite,
          recommendedLevel: 12,
          enemyIds: ['elite_guard', 'elite_mage', 'elite_guard'],
          rewards: QuestReward(coin: 6000, grain: 4000, exp: 2000),
        ),
        Stage(
          id: '5-4',
          name: '帝王之路',
          type: StageType.boss,
          recommendedLevel: 15,
          enemyIds: ['final_boss', 'elite_guard', 'elite_mage'],
          rewards: QuestReward(
            coin: 15000,
            grain: 10000,
            exp: 5000,
            reputation: 100,
          ),
        ),
      ],
    ),
  ];

  // 初始任务
  static List<Quest> getInitialQuests() => [
    // ===== 主线任务 =====
    Quest(
      id: 'main_001',
      name: '黄巾初乱',
      description: '黄巾贼众围困村庄，百姓求援。出兵击退黄巾军，保卫平原城！\n\n「大人！黄巾贼人正在屠村，再不救援就来不及了！」',
      type: QuestType.main,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [
        QuestObjective(type: 'battle', targetId: '1-2', requiredCount: 1),
      ],
      rewards: QuestReward(coin: 1000, grain: 800, exp: 300, reputation: 5),
    ),
    Quest(
      id: 'main_002',
      name: '守卫家园',
      description: '黄巾渠帅盘踞县城，四处烧杀抢掠。击败贼首，平定地方！\n\n「大人，若不斩杀贼首，黄巾军将卷土重来！」',
      type: QuestType.main,
      requiredLevel: 1,
      status: QuestStatus.locked,
      objectives: [
        QuestObjective(type: 'battle', targetId: '1-5', requiredCount: 1),
      ],
      rewards: QuestReward(coin: 3000, grain: 2000, exp: 800, reputation: 20),
    ),
    Quest(
      id: 'main_003',
      name: '讨伐董卓',
      description:
          '董卓祸乱朝纲，废立天子，天怒人怨。十八路诸侯会盟酸枣，共商讨董大计。前往虎牢关前哨探敌情！\n\n「今各兴义兵，共赴国难！」',
      type: QuestType.main,
      requiredLevel: 5,
      status: QuestStatus.locked,
      objectives: [
        QuestObjective(type: 'battle', targetId: '2-2', requiredCount: 1),
      ],
      rewards: QuestReward(coin: 4000, grain: 3000, exp: 1000, reputation: 15),
    ),
    Quest(
      id: 'main_004',
      name: '战神吕布',
      description:
          '吕布亲自出阵，人中吕布马中赤兔！他在虎牢关前已连斩数将，无人敢战。你能否一战成名？\n\n「吕布在此，谁敢来决一死战！」',
      type: QuestType.main,
      requiredLevel: 7,
      status: QuestStatus.locked,
      objectives: [
        QuestObjective(type: 'battle', targetId: '2-4', requiredCount: 1),
      ],
      rewards: QuestReward(coin: 8000, grain: 5000, exp: 2000, reputation: 40),
    ),
    Quest(
      id: 'main_005',
      name: '群雄割据',
      description:
          '袁绍大军压境，官渡之战一触即发。颜良、文丑乃河北名将，必须斩杀以挫敌军锐气！\n\n「斩颜良、诛文丑，方可挫败袁绍！」',
      type: QuestType.main,
      requiredLevel: 9,
      status: QuestStatus.locked,
      objectives: [
        QuestObjective(type: 'battle', targetId: '3-5', requiredCount: 1),
        QuestObjective(type: 'battle', targetId: '3-6', requiredCount: 1),
      ],
      rewards: QuestReward(coin: 10000, grain: 8000, exp: 3000, reputation: 50),
    ),
    Quest(
      id: 'main_006',
      name: '赤壁之火',
      description:
          '曹操大军压境，号称八十万。孙刘联军决战赤壁，万事俱备只欠东风。火烧曹营，一战定天下！\n\n「今夜东风已起，全军出击！」',
      type: QuestType.main,
      requiredLevel: 10,
      status: QuestStatus.locked,
      objectives: [
        QuestObjective(type: 'battle', targetId: '4-4', requiredCount: 1),
      ],
      rewards: QuestReward(coin: 12000, grain: 8000, exp: 3000, reputation: 40),
    ),
    Quest(
      id: 'main_007',
      name: '问鼎天下',
      description: '天下三分已定，最终决战的时刻到了。击败最终的守卫者，问鼎天下！\n\n「分久必合，天下终将一统！」',
      type: QuestType.main,
      requiredLevel: 15,
      status: QuestStatus.locked,
      objectives: [
        QuestObjective(type: 'battle', targetId: '5-4', requiredCount: 1),
      ],
      rewards: QuestReward(
        coin: 20000,
        grain: 15000,
        exp: 8000,
        reputation: 100,
      ),
    ),

    // ===== 支线任务 =====
    Quest(
      id: 'side_001',
      name: '招贤纳士',
      description: '前往酒馆招募一名武将，壮大队伍。',
      type: QuestType.side,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [QuestObjective(type: 'recruit', requiredCount: 1)],
      rewards: QuestReward(coin: 500, exp: 200),
    ),
    Quest(
      id: 'side_002',
      name: '广纳英才',
      description: '招募5名武将，组建强大的队伍。',
      type: QuestType.side,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [QuestObjective(type: 'recruit', requiredCount: 5)],
      rewards: QuestReward(coin: 2000, grain: 1000, exp: 500),
    ),
    Quest(
      id: 'side_003',
      name: '初建基业',
      description: '升级任意建筑到2级，开始发展城池。',
      type: QuestType.side,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [QuestObjective(type: 'build', requiredCount: 1)],
      rewards: QuestReward(coin: 800, grain: 500, exp: 200),
    ),
    Quest(
      id: 'side_004',
      name: '城池发展',
      description: '升级建筑累计10次，让城池繁荣起来。',
      type: QuestType.side,
      requiredLevel: 2,
      status: QuestStatus.locked,
      objectives: [QuestObjective(type: 'build', requiredCount: 10)],
      rewards: QuestReward(coin: 3000, grain: 2000, exp: 800, reputation: 10),
    ),
    Quest(
      id: 'side_005',
      name: '初战告捷',
      description: '完成3场战斗，积累战斗经验。',
      type: QuestType.side,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [QuestObjective(type: 'battle_total', requiredCount: 3)],
      rewards: QuestReward(coin: 1500, grain: 1000, exp: 400),
    ),
    Quest(
      id: 'side_006',
      name: '百战之师',
      description: '完成20场战斗，成为久经沙场的将领。',
      type: QuestType.side,
      requiredLevel: 3,
      status: QuestStatus.locked,
      objectives: [QuestObjective(type: 'battle_total', requiredCount: 20)],
      rewards: QuestReward(coin: 5000, grain: 3000, exp: 1500, reputation: 20),
    ),
    Quest(
      id: 'side_007',
      name: '军备充实',
      description: '给武将装备任意道具，提升战斗力。',
      type: QuestType.side,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [QuestObjective(type: 'equip', requiredCount: 1)],
      rewards: QuestReward(coin: 600, exp: 150),
    ),
    Quest(
      id: 'side_008',
      name: '武将养成',
      description: '将任意武将升级到5级。',
      type: QuestType.side,
      requiredLevel: 2,
      status: QuestStatus.locked,
      objectives: [QuestObjective(type: 'general_level', requiredCount: 1)],
      rewards: QuestReward(coin: 2000, exp: 600, reputation: 5),
    ),

    // ===== 每日任务 =====
    Quest(
      id: 'daily_001',
      name: '日常巡查',
      description: '进行一次内政治理，维护城池秩序。',
      type: QuestType.daily,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [QuestObjective(type: 'politics', requiredCount: 1)],
      rewards: QuestReward(coin: 300, grain: 200, exp: 100),
    ),
    Quest(
      id: 'daily_002',
      name: '勤政爱民',
      description: '进行3次内政治理，做个好城主。',
      type: QuestType.daily,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [QuestObjective(type: 'politics', requiredCount: 3)],
      rewards: QuestReward(coin: 800, grain: 500, exp: 250),
    ),
    Quest(
      id: 'daily_003',
      name: '出征讨伐',
      description: '完成1场战斗，保卫疆土。',
      type: QuestType.daily,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [QuestObjective(type: 'battle_total', requiredCount: 1)],
      rewards: QuestReward(coin: 500, grain: 300, exp: 150),
    ),
    Quest(
      id: 'daily_004',
      name: '战功赫赫',
      description: '完成3场战斗，勇冠三军。',
      type: QuestType.daily,
      requiredLevel: 2,
      status: QuestStatus.locked,
      objectives: [QuestObjective(type: 'battle_total', requiredCount: 3)],
      rewards: QuestReward(coin: 1200, grain: 800, exp: 400),
    ),
    Quest(
      id: 'daily_005',
      name: '招募武将',
      description: '在酒馆招募1名武将。',
      type: QuestType.daily,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [QuestObjective(type: 'recruit', requiredCount: 1)],
      rewards: QuestReward(coin: 400, exp: 100),
    ),
    Quest(
      id: 'daily_006',
      name: '征收赋税',
      description: '进行一次征收赋税，充实府库。',
      type: QuestType.daily,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [QuestObjective(type: 'tax', requiredCount: 1)],
      rewards: QuestReward(coin: 200, exp: 50),
    ),

    // ===== 成就任务 =====
    Quest(
      id: 'achieve_001',
      name: '初出茅庐',
      description: '完成第一章所有关卡。',
      type: QuestType.achievement,
      requiredLevel: 1,
      status: QuestStatus.active,
      objectives: [
        QuestObjective(type: 'chapter_clear', targetId: '1', requiredCount: 1),
      ],
      rewards: QuestReward(coin: 5000, grain: 3000, exp: 1000, reputation: 30),
    ),
    Quest(
      id: 'achieve_002',
      name: '虎牢关之战',
      description: '完成第二章所有关卡。',
      type: QuestType.achievement,
      requiredLevel: 5,
      status: QuestStatus.locked,
      objectives: [
        QuestObjective(type: 'chapter_clear', targetId: '2', requiredCount: 1),
      ],
      rewards: QuestReward(coin: 8000, grain: 5000, exp: 2000, reputation: 50),
    ),
    Quest(
      id: 'achieve_003',
      name: '群雄之主',
      description: '拥有10名武将。',
      type: QuestType.achievement,
      requiredLevel: 3,
      status: QuestStatus.locked,
      objectives: [QuestObjective(type: 'generals_count', requiredCount: 10)],
      rewards: QuestReward(coin: 5000, grain: 3000, exp: 1500, reputation: 20),
    ),
    Quest(
      id: 'achieve_004',
      name: '富甲一方',
      description: '累计拥有10000铜钱。',
      type: QuestType.achievement,
      requiredLevel: 3,
      status: QuestStatus.locked,
      objectives: [QuestObjective(type: 'coin_reach', requiredCount: 10000)],
      rewards: QuestReward(coin: 3000, exp: 800, reputation: 15),
    ),
    Quest(
      id: 'achieve_005',
      name: '百战将军',
      description: '累计完成50场战斗。',
      type: QuestType.achievement,
      requiredLevel: 5,
      status: QuestStatus.locked,
      objectives: [QuestObjective(type: 'battle_total', requiredCount: 50)],
      rewards: QuestReward(coin: 10000, grain: 8000, exp: 3000, reputation: 50),
    ),
  ];

  // 剧情事件
  static List<GameEvent> getAllEvents() => [
    GameEvent(
      id: 'evt_refugees',
      title: '流民入城',
      description:
          '数百流民跪在城门外，请求入城避难。\n粮草本就不多，守军担心其中混有奸细。\n\n“大人，求求您收留我们吧！黄巾贼杀人如麻，我们已无处可去……”',
      choices: [
        EventChoice(
          text: '开门接纳，安置流民',
          effects: {'morale': 10, 'grain': -500},
          resultText: '百姓感恩涕零，纷纷称赞主公仁德。城中人口增加，民心大振。',
        ),
        EventChoice(
          text: '发放粮草，但不许入城',
          effects: {'morale': 3, 'grain': -300},
          resultText: '流民接过粮草，跪谢而去。虽未入城，但也算尽了仁义。',
        ),
        EventChoice(
          text: '紧闭城门，驱逐流民',
          effects: {'morale': -10, 'reputation': -5},
          resultText: '流民含恨离去，城中议论纷纷。有士兵低声议论：“若有一日我们也沦为难民……”',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_merchant',
      title: '商队来访',
      description:
          '一支来自西域的商队途经此地，队长求见城主。\n\n“大人，我等远道而来，愿以优惠价格出售物资。乱世之中，互通有无方能共存。”',
      choices: [
        EventChoice(
          text: '购买粮草（花费500铜钱）',
          effects: {'coin': -500, 'grain': 1000},
          resultText: '交易达成，粮仓充盈。商队长笑道：“大人爽快，日后定当再来。”',
        ),
        EventChoice(
          text: '购买铁矿（花费400铜钱）',
          effects: {'coin': -400, 'iron': 600},
          resultText: '精铁入手，铁匠欣喜不已：“好铁！可锻造上等兵器。”',
        ),
        EventChoice(
          text: '征收商税（强制收取）',
          effects: {'coin': 300, 'reputation': -8, 'morale': -3},
          resultText: '商队被迫缴税，悻悻离去。此后商队再不愿途经此地。',
        ),
        EventChoice(text: '婉拒商队', effects: {}, resultText: '商队离去，一切如常。'),
      ],
    ),
    GameEvent(
      id: 'evt_scholar',
      title: '名士来访',
      description: '一位名士慕名来访，此人曾游历四方，见识广博。\n\n“久闻大人仁德之名，特来拜会。在下有些浅见，不知当讲不当讲。”',
      choices: [
        EventChoice(
          text: '以礼相待，设宴款待',
          effects: {'reputation': 8, 'morale': 5, 'coin': -200},
          resultText: '名士赞赏有加，临走时道：“大人礼贤下士，他日必成大器。”名声远播。',
        ),
        EventChoice(
          text: '请教兵法，虚心学习',
          effects: {'reputation': 3, 'exp': 200},
          resultText: '一番论道，颇有收获。名士传授了一些排兵布阵之法，受益匪浅。',
        ),
        EventChoice(
          text: '延请为幕僚',
          effects: {'reputation': 5, 'exp': 150, 'coin': -500},
          resultText: '名士被诚意打动，决定暂留城中指点政务。城池治理水平提升。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_bandits',
      title: '山贼骚扰',
      description:
          '斥候来报，城外三十里处出现一伙山贼，约百余众。\n频繁骚扰过往商旅，百姓人心惶惶。\n\n“大人，若不剿灭此伙贼人，商路断绝，后果不堪设想！”',
      choices: [
        EventChoice(
          text: '出兵剿灭',
          effects: {'soldiers': -50, 'reputation': 5, 'coin': 200},
          resultText: '山贼被剿灭，缴获赃银二百两。道路恢复安宁，商旅称便。',
        ),
        EventChoice(
          text: '招安收编',
          effects: {'soldiers': 30, 'reputation': -3, 'grain': -200},
          resultText: '山贼头目率众归降，虽增兵三十人，但军中老兵颇有微词。',
        ),
        EventChoice(
          text: '置之不理',
          effects: {'morale': -5, 'coin': -300},
          resultText: '山贼越发猖獗，商旅损失惨重，税收锐减。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_famine',
      title: '天降旱灾',
      description: '连月无雨，田地龟裂，粮食歉收。\n百姓面有菜色，军中粮草告急。\n\n“大人，今年收成不及往年三成，恐有饥荒之虞！”',
      choices: [
        EventChoice(
          text: '开仓放粮，与民共苦',
          effects: {'morale': 15, 'grain': -800, 'reputation': 10},
          resultText: '主公与百姓同甘共苦，民心归附。虽粮草紧缺，但人心稳定。',
        ),
        EventChoice(
          text: '缩减军粮，优先百姓',
          effects: {'morale': 8, 'soldiers': -30, 'grain': -400},
          resultText: '军粮缩减，部分士兵不堪饥饿逃散。但百姓感恩戴德。',
        ),
        EventChoice(
          text: '征收富户余粮',
          effects: {'grain': 500, 'reputation': -5, 'morale': -3},
          resultText: '强行征收富户余粮，虽解燃眉之急，但得罪了城中豪绅。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_plague',
      title: '疫病流行',
      description: '城中突发疫病，患者日增。\n医馆人满为患，百姓惶恐不安。\n\n“大人，若不加以控制，恐怕全城蔓延！”',
      choices: [
        EventChoice(
          text: '封锁疫区，全力救治',
          effects: {'coin': -600, 'morale': 5, 'soldiers': -20},
          resultText: '投入大量银两购置药材，虽损失了些士兵，但疫情得到控制。',
        ),
        EventChoice(
          text: '延请名医，广施汤药',
          effects: {'coin': -400, 'morale': 10, 'reputation': 5},
          resultText: '名医开出良方，疫情渐息。百姓称颂主公仁德。',
        ),
        EventChoice(
          text: '听天由命，不予干预',
          effects: {'morale': -15, 'soldiers': -80, 'reputation': -8},
          resultText: '疫情蔓延，死伤无数。城中人心惶惶，怨声载道。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_treasure',
      title: '古墓宝藏',
      description: '探子在城外发现一处古墓，据传为前朝王侯之墓。\n\n“大人，墓中似有大量珍宝，但也可能有机关陷阱……”',
      choices: [
        EventChoice(
          text: '派人探索',
          effects: {'coin': 1500, 'iron': 300, 'soldiers': -10},
          resultText: '探得大量金银珠宝和精铁！虽有少数士兵受伤，但收获颇丰。',
        ),
        EventChoice(
          text: '谨慎探索，小心行事',
          effects: {'coin': 800, 'iron': 150},
          resultText: '谨慎行事，虽收获不及预期，但无人员伤亡。',
        ),
        EventChoice(
          text: '封存古墓，不予惊扰',
          effects: {'reputation': 5, 'morale': 3},
          resultText: '封存古墓，百姓称赞主公敬畏先人。声望提升。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_general_visit',
      title: '武将投奔',
      description:
          '一名落魄武将来到城下，自称曾效力于某路诸侯。\n如今兵败流落至此，愿为主公效力。\n\n“在下虽不才，但愿为主公鞍前马后，肝脑涂地！”',
      choices: [
        EventChoice(
          text: '收纳为将',
          effects: {'reputation': 3, 'grain': -100},
          resultText: '武将感恩涕零，发誓效忠。城中又添一员战将。',
        ),
        EventChoice(
          text: '考验武艺后收纳',
          effects: {'reputation': 5, 'grain': -100, 'exp': 100},
          resultText: '经过校场比武，此人武艺确实不凡，被正式收纳为将。',
        ),
        EventChoice(text: '婉言谢绝', effects: {}, resultText: '武将遗憾离去，寻找其他明主。'),
      ],
    ),
    GameEvent(
      id: 'evt_spy',
      title: '间谍潜入',
      description: '守军抓到一名可疑人物，经审讯确认为敌方间谍。\n\n“大人，此人已潜入城中多日，恐已探得不少军情！”',
      choices: [
        EventChoice(
          text: '就地正法',
          effects: {'morale': 5, 'reputation': -3},
          resultText: '间谍被处决，军中士气提升。但外界传闻主公残暴。',
        ),
        EventChoice(
          text: '关押审讯，获取情报',
          effects: {'exp': 150, 'reputation': 2},
          resultText: '经过审讯，获取了敌方部署情报。知己知彼，百战不殆。',
        ),
        EventChoice(
          text: '放归并传递假情报',
          effects: {'reputation': 8, 'exp': 100},
          resultText: '妙计！放归间谍并让其带回假情报，敌方中计。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_festival',
      title: '丰收庆典',
      description:
          '今年风调雨顺，五谷丰登。百姓欢欣鼓舞，请求举办庆典。\n\n“大人，今年收成极好！百姓们想办一场庆典，感谢上苍庇佑。”',
      choices: [
        EventChoice(
          text: '大办庆典，与民同乐',
          effects: {'morale': 15, 'coin': -300, 'grain': -200, 'reputation': 5},
          resultText: '庆典热闹非凡，百姓载歌载舞。主公与民同乐，传为佳话。',
        ),
        EventChoice(
          text: '小规模庆祝，节省开支',
          effects: {'morale': 8, 'coin': -100},
          resultText: '虽规模不大，但百姓也很满足。城中洋溢着一片喜悦。',
        ),
        EventChoice(
          text: '存粮备战，取消庆典',
          effects: {'grain': 300, 'morale': -5},
          resultText: '取消庆典，粮食存入仓库。百姓虽有些失望，但也理解主公深谋远虑。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_dream',
      title: '奇梦预兆',
      description: '主公夜得一梦，梦见金龙盘踞城头，又有猛虎下山。\n\n幕僚道：“此梦非同寻常，或为吉凶参半之兆。”',
      choices: [
        EventChoice(
          text: '请术士解梦',
          effects: {'coin': -200, 'exp': 100, 'morale': 5},
          resultText: '术士道：“金龙为帝王之象，猛虎主兵戈。主公将有大事发生。”虽花费不少，但心中有所准备。',
        ),
        EventChoice(
          text: '不信鬼神，一笑置之',
          effects: {'reputation': 3},
          resultText: '主公豁达大度，不为鬼神所惑。左右皆赞主公明智。',
        ),
        EventChoice(
          text: '祈福消灾',
          effects: {'coin': -100, 'morale': 8, 'reputation': 2},
          resultText: '主公前往庙中祈福，百姓见之主心安。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_rebellion',
      title: '军中哗变',
      description: '部分士兵因长期征战、粮饷不足，心生不满。\n\n“大人，军中有哗变之兆！需尽快处置，否则后果不堪设想！”',
      choices: [
        EventChoice(
          text: '安抚军心，发放赏银',
          effects: {'coin': -500, 'morale': 10, 'soldiers': 20},
          resultText: '发放赏银后，军心大定。士兵们誓死效忠，再无二心。',
        ),
        EventChoice(
          text: '严惩首恶，杀鸡儆猴',
          effects: {'soldiers': -30, 'morale': -5, 'reputation': -3},
          resultText: '处决了带头哗变的士兵，虽震慑了全军，但也留下了阴影。',
        ),
        EventChoice(
          text: '亲赴军营，与士卒同食',
          effects: {'morale': 15, 'reputation': 8, 'grain': -200},
          resultText: '主公亲赴军营，与士兵同吃同住。士兵感动涕零，军心空前凝聚。',
        ),
      ],
    ),
    // ===== 第一章·黄巾乱起 专属事件 =====
    GameEvent(
      id: 'evt_ch1_yellow_turban_prophecy',
      title: '黄天当立',
      description:
          '斥候截获一封黄巾军密信，内容是张角写给各地渠帅的檄文：\n\n「苍天已死，黄天当立。岁在甲子，天下大吉。凡我教众，头绑黄巾，共举大事！」\n\n你细读全文，发现张角不仅在传教，更在各地埋设了「符水」据点，用以治疗伤病、蛊惑百姓。\n\n「难怪黄巾军能迅速席卷八州……」谋士眉头紧锁，「大人，若不从根子上破解其妖术惑民之法，只怕黄巾军会越打越多。」',
      choices: [
        EventChoice(
          text: '焚烧密信，全力备战',
          effects: {'exp': 100, 'morale': 5},
          resultText: '你下令焚烧密信，将全部精力投入到与黄巾军的战斗中。不管什么妖术，刀剑才是硬道理。',
        ),
        EventChoice(
          text: '研究符水，破解妖术',
          effects: {'exp': 200, 'reputation': 8, 'coin': -300},
          resultText: '你派人研究黄巾符水的奥秘，发现不过是普通草药加上心理暗示。破解之法传开后，百姓不再盲从，黄巾军势力有所削弱。',
        ),
        EventChoice(
          text: '将密信呈报上级',
          effects: {'reputation': 5, 'coin': 200},
          resultText: '你将密信呈报朝廷，获得了上司的赞赏和赏赐。但朝廷的反应迟缓，密信石沉大海。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_ch1_village_rescue',
      title: '困守村庄',
      description:
          '一名村民冒死突围来报：黄巾军已将附近村庄包围，村中老幼三百余人命悬一线。\n\n「大人！黄巾贼人正在屠村，再不救援就来不及了！」\n\n但你的兵力本就不足，分兵救援恐有风险。副将低声提醒：「大人，万一是诱兵之计……」',
      choices: [
        EventChoice(
          text: '亲率精锐急行军救援',
          effects: {'soldiers': -30, 'morale': 15, 'reputation': 10},
          resultText: '你亲自率兵急行军赶到，击退了黄巾军。村民跪地磕头：「救命之恩，没齿难忘！」消息传开，更多百姓愿意投奔。',
        ),
        EventChoice(
          text: '派偏师前往，主力守城',
          effects: {'soldiers': -15, 'morale': 5, 'reputation': 5},
          resultText: '偏师赶到时战斗已近尾声，救下了部分村民。虽不完美，但也尽了力。',
        ),
        EventChoice(
          text: '坚守城池，等待时机',
          effects: {'morale': -8, 'reputation': -5},
          resultText: '你没有出兵。第二天，斥候回报：村庄已被屠尽，三百余口无一生还。城中百姓闻之黯然。',
        ),
      ],
    ),
    // ===== 第二章·董卓入京 专属事件 =====
    GameEvent(
      id: 'evt_ch2_emperor_decree',
      title: '矫诏之争',
      description:
          '一道来自洛阳的诏书传至各地：「拜董卓为相国，赞拜不名，入朝不趋，剑履上殿。」\n\n群臣哗然。\n\n你的幕僚分析道：「这分明是董卓胁迫天子下的矫诏！若接受，便是认贼作父；若抗诏，便是公然与朝廷为敌。」\n\n武将怒道：「董卓欺人太甚！不如起兵讨之！」',
      choices: [
        EventChoice(
          text: '拒绝矫诏，发布讨贼檄文',
          effects: {'reputation': 15, 'morale': 10, 'coin': -500},
          resultText: '你公开发布讨贼檄文，誓与董卓不两立。檄文传遍天下，有志之士纷纷来投。',
        ),
        EventChoice(
          text: '暂不表态，暗中联络诸侯',
          effects: {'reputation': 5, 'exp': 150},
          resultText: '你采取稳健策略，暗中与其他诸侯联络，共商讨董之策。虽不张扬，但也未失人心。',
        ),
        EventChoice(
          text: '接受诏书，保存实力',
          effects: {'coin': 500, 'reputation': -10, 'morale': -8},
          resultText: '你暂时接受了矫诏，保住了现有地位。但部下中有人露出了失望的神色……',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_ch2_hulao_pass',
      title: '虎牢关前',
      description:
          '盟军兵临虎牢关下，关内董卓大将华雄连斩数将，盟军士气大挫。\n\n袁绍在帐中叹息：「可惜吾上将颜良、文丑未至！若有一人在此，何惧华雄？」\n\n这时，你注意到关羽按刀而立，眉宇间有请战之意。但盟军中有人嘀咕：「一个马弓手，也想与华雄交手？」',
      choices: [
        EventChoice(
          text: '力挺关羽出战',
          effects: {'reputation': 10, 'exp': 200},
          resultText: '你力排众议推荐关羽。关羽提刀出帐，片刻后提华雄首级而入，酒尚温也！盟军士气大振，关羽一战成名。',
        ),
        EventChoice(
          text: '亲自请缨挑战',
          effects: {'exp': 300, 'soldiers': -20, 'reputation': 5},
          resultText: '你亲自率兵挑战华雄。一场血战后，终于将其斩杀。此战让你名震诸侯，但也损失了不少兵力。',
        ),
        EventChoice(
          text: '静观其变，等待时机',
          effects: {'exp': 100},
          resultText: '你选择观望。最终关羽还是请战并斩杀了华雄。虽未亲手解决，但也保存了实力。',
        ),
      ],
    ),
    // ===== 第三章·群雄割据 专属事件 =====
    GameEvent(
      id: 'evt_ch3_guandu_prelude',
      title: '官渡风云',
      description:
          '官渡之战前夕，曹操与袁绍两军对峙。\n\n谋士许攸深夜来访，神秘兮兮地说：「我有一计，可破袁绍。但我需先见曹操，你可为我引荐？」\n\n许攸本是袁绍手下谋士，如今却来投曹。你该如何处置？',
      choices: [
        EventChoice(
          text: '立即引荐给曹操',
          effects: {'reputation': 10, 'exp': 200, 'coin': 500},
          resultText: '你引荐许攸见曹操。曹操跌足出迎，许攸献计火烧乌巢，果然大破袁绍！你因此立下大功，获得丰厚赏赐。',
        ),
        EventChoice(
          text: '先审讯核实再引荐',
          effects: {'reputation': 5, 'exp': 100},
          resultText: '你谨慎地核实了许攸的意图，确认无误后才引荐。虽晚了一步，但也确保了一切稳妥。',
        ),
        EventChoice(
          text: '拒绝引荐，自己留下',
          effects: {'exp': 150, 'reputation': -3},
          resultText: '你将许攸留在身边，从他口中套取了不少袁绍的军事情报。但曹操后来知道此事，对你颇有微词。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_ch3_taoyuan_oath',
      title: '桃园结义',
      description:
          '刘备在徐州被吕布偷袭，失去立足之地，率残部来投。\n\n刘备见到你，拱手道：「备不才，兵微将寡，但关、张二人皆有万夫不当之勇。愿与将军结盟，共图大事。」\n\n关羽持刀而立，张飞抱臂在旁，两人目光炯炯。',
      choices: [
        EventChoice(
          text: '热情接纳，结为兄弟',
          effects: {'morale': 15, 'reputation': 10, 'grain': -300},
          resultText: '你与刘备桃园结义，结为兄弟。关羽、张飞也正式加入阵营！「不求同年同月同日生，但求同年同月同日死！」',
        ),
        EventChoice(
          text: '提供粮草，保持距离',
          effects: {'grain': -500, 'reputation': 5},
          resultText: '你提供了粮草支持，但没有深度结盟。刘备感激而去，在附近另立营寨。',
        ),
        EventChoice(
          text: '婉言谢绝',
          effects: {'reputation': -5},
          resultText: '你婉拒了刘备的提议。刘备叹了口气，带着残部黯然离去。',
        ),
      ],
    ),
    // ===== 第四章·赤壁之战 专属事件 =====
    GameEvent(
      id: 'evt_ch4_cao_letter',
      title: '曹操劝降书',
      description:
          '赤壁之战前，曹操遣使送来一封亲笔信：\n\n「今统兵八十万，方与将军会猎于吴。」\n\n信中语气看似客气，实为威胁。使者傲慢地递上信件，斜眼打量着你。\n\n左右武将怒不可遏，文臣们则面面相觎。',
      choices: [
        EventChoice(
          text: '斩来使以明志',
          effects: {'morale': 15, 'reputation': 10, 'soldiers': 10},
          resultText: '你拍案而起：「曹操名为汉相，实为汉贼！」当即下令斩使。全军士气高涨，誓与曹军决一死战！',
        ),
        EventChoice(
          text: '回信拒绝，但不斩使',
          effects: {'reputation': 5, 'morale': 5},
          resultText: '你礼貌地回绝了曹操的招降，并放回使者。曹操闻之冷哼：「不识抬举。」',
        ),
        EventChoice(
          text: '假装动摇，拖延时间',
          effects: {'exp': 150, 'reputation': -3},
          resultText: '你假装考虑投降，拖延时间以待战机。虽然策略有效，但军中有些人开始动摇……',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_ch4_fire_boats',
      title: '火船奇袭',
      description:
          '赤壁之战进入关键时刻，黄盖的火船已经准备就绪。\n\n但风向突然转变！原本东南风变成了西北风，火船若现在出发，火势会反烧己方。\n\n诸将紧张地望向诸葛亮。诸葛亮却淡定地站在七星坛上，羽扇轻摇。\n\n「诸位勿忧，风很快就会变。」',
      choices: [
        EventChoice(
          text: '信任诸葛亮，等待风变',
          effects: {'reputation': 10, 'exp': 200, 'morale': 10},
          resultText: '你选择了信任。片刻后，风向果然转为东南！火船顺风而下，曹军水寨瞬间化为火海。赤壁之战，大获全胜！',
        ),
        EventChoice(
          text: '不等风变，强行出击',
          effects: {'soldiers': -50, 'reputation': -5},
          resultText: '你下令强行出击，但风向不利，火船反烧己方。幸好诸葛亮及时调整，才没有酿成大祸。',
        ),
        EventChoice(
          text: '改用火攻以外的方案',
          effects: {'exp': 100, 'coin': -300},
          resultText: '你准备了备用方案。虽然效果不如火攻，但总算没有贻误战机。',
        ),
      ],
    ),
    // ===== 第五章·问鼎天下 专属事件 =====
    GameEvent(
      id: 'evt_ch5_final_choice',
      title: '天下抉择',
      description:
          '最终决战之前，谋士深夜来访，神色凝重：\n\n「主公，有件事我必须告诉您。无论此战胜负，您都面临一个选择——」\n\n「若胜，您是匡扶汉室、还政于天子？还是……开创新朝？」\n\n「若败……则一切休谈。」\n\n帐外月色如水，远处军营灯火通明。将士们都在为明天的大战做准备。',
      choices: [
        EventChoice(
          text: '匡扶汉室，以忠义立身',
          effects: {'reputation': 20, 'morale': 15},
          resultText: '你决定匡扶汉室，以忠义之名征伐天下。将士们感佩你的仁德，誓死相随。「汉室可兴，天下可定！」',
        ),
        EventChoice(
          text: '开创新朝，建立不世之功',
          effects: {'reputation': 10, 'exp': 300, 'morale': 10},
          resultText: '你决定开创新朝，结束这数百年的乱世。将士们虽然惊讶，但也纷纷拥戴。「新朝将开，万世基业！」',
        ),
        EventChoice(
          text: '先打赢再说，其他事后再议',
          effects: {'exp': 200, 'morale': 5},
          resultText: '你决定先专心于明天的决战。谋士点头：「主公说得对，先打赢再说。」全军上下，斗志昂扬。',
        ),
      ],
    ),
    GameEvent(
      id: 'evt_ch5_veteran_advice',
      title: '老将之谋',
      description:
          '大战在即，一位年过七自的老将求见。\n\n他曾跟随你征战多年，身上伤疤无数。如今虽然年迈，但目光仍然炯炯有神。\n\n「主公，老仆有一言，不知当讲不当讲。」\n\n「明日之战，敌军兵力在我之上，不可硬拼。老仆有一计——佯败诱敌深入，再伏兵四起，可一战而定。」\n\n他展开一张地图，指着上面的山谷：「此处地形险要，正是设伏的好地方。」',
      choices: [
        EventChoice(
          text: '采纳老将之计，设伏山谷',
          effects: {'exp': 300, 'reputation': 10, 'morale': 10},
          resultText: '你采纳了老将的计策。明日之战，佯败诱敌入山谷，伏兵四起，敌军大乱！此计堪称神来之笔。',
        ),
        EventChoice(
          text: '感谢老将，但坚持正面决战',
          effects: {'exp': 150, 'morale': 5, 'soldiers': -20},
          resultText: '你感谢老将的建议，但决定正面决战。一场硬仗下来，虽然获胜但损失不小。',
        ),
        EventChoice(
          text: '让老将率偏师执行伏击',
          effects: {'exp': 200, 'reputation': 5},
          resultText: '你让老将率领一支偏师执行伏击计划，主力正面应对。两路夹击，效果出奇的好！',
        ),
      ],
    ),
  ];

  // 默认建筑
  static List<Building> getDefaultBuildings() {
    return BuildingType.values.map((type) {
      return Building(
        type: type,
        name: buildingNames[type] ?? '',
        level: type == BuildingType.government ? 1 : 0,
        maxLevel: 10,
        upgradeCost: _buildingUpgradeCost(type),
        upgradeTimeSeconds: 120,
      );
    }).toList();
  }

  static Map<String, int> _buildingUpgradeCost(BuildingType type) {
    switch (type) {
      case BuildingType.government:
        return {'coin': 1000, 'wood': 500};
      case BuildingType.farm:
        return {'coin': 500, 'wood': 200};
      case BuildingType.market:
        return {'coin': 600, 'wood': 300};
      case BuildingType.lumberMill:
        return {'coin': 400, 'wood': 100};
      case BuildingType.ironWorks:
        return {'coin': 500, 'iron': 100};
      case BuildingType.barracks:
        return {'coin': 800, 'wood': 400};
      case BuildingType.trainingGround:
        return {'coin': 700, 'wood': 300};
      case BuildingType.tavern:
        return {'coin': 600, 'wood': 250};
      case BuildingType.blacksmith:
        return {'coin': 500, 'iron': 200};
      case BuildingType.academy:
        return {'coin': 800, 'wood': 300};
      case BuildingType.postStation:
        return {'coin': 400, 'wood': 200};
      case BuildingType.wall:
        return {'coin': 600, 'wood': 400, 'iron': 200};
    }
  }

  // 默认阵型
  static List<Formation> getDefaultFormations() => [
    Formation(
      id: 'fengbing',
      name: '锋矢阵',
      description: '前锋突出，如矢之锐。适合以攻为主、突破敌阵的战术。',
      bonuses: {'attackPercent': 0.10},
      slots: [
        [null, null],
        [null, null],
        [null],
      ],
    ),
    Formation(
      id: 'yanzhen',
      name: '雁行阵',
      description: '如大雁列队，两翼展开。攻守兼备，行动迅速。',
      bonuses: {'speedPercent': 0.15},
      slots: [
        [null, null],
        [null, null],
        [null],
      ],
    ),
    Formation(
      id: 'heyi',
      name: '鹤翼阵',
      description: '两翼如鹤展翅，包抄夹击。兼顾攻防，适合持久战。',
      bonuses: {'defensePercent': 0.10, 'attackPercent': 0.05},
      slots: [
        [null, null],
        [null, null],
        [null],
      ],
    ),
    Formation(
      id: 'fangyuan',
      name: '方圆阵',
      description: '四面防御，固若金汤。适合以守为攻、消耗敌军。',
      bonuses: {'defensePercent': 0.20},
      slots: [
        [null, null, null],
        [null],
        [null],
      ],
      frontSlots: 3,
      midSlots: 1,
      backSlots: 1,
    ),
    Formation(
      id: 'changshe',
      name: '长蛇阵',
      description: '首尾相应，灵活多变。如蛇之蜿蝘，攻其不备。',
      bonuses: {'speedPercent': 0.10, 'attackPercent': 0.05},
      slots: [
        [null],
        [null, null],
        [null, null],
      ],
      frontSlots: 1,
      midSlots: 2,
      backSlots: 2,
    ),
    Formation(
      id: 'yulin',
      name: '鱼鳞阵',
      description: '层层叠叠，如鱼之鳞。前赴后继，攻势连绵。',
      bonuses: {'attackPercent': 0.15},
      slots: [
        [null, null],
        [null, null],
        [null],
      ],
    ),
  ];

  // 初始道具
  static List<GameItem> getDefaultItems() => [
    // 消耗品
    GameItem(
      id: 'herb',
      name: '药草',
      description: '恢复武将20%生命值',
      quality: Quality.white,
      type: ItemType.consumable,
      quantity: 5,
    ),
    GameItem(
      id: 'great_herb',
      name: '上等药草',
      description: '恢复武将50%生命值',
      quality: Quality.green,
      type: ItemType.consumable,
      quantity: 2,
    ),
    GameItem(
      id: 'recruit_token',
      name: '普通招募令',
      description: '用于在酒馆招募武将',
      quality: Quality.green,
      type: ItemType.consumable,
      quantity: 3,
    ),
    GameItem(
      id: 'adv_recruit_token',
      name: '高级招募令',
      description: '用于在酒馆进行高级招募',
      quality: Quality.blue,
      type: ItemType.consumable,
      quantity: 1,
    ),
    GameItem(
      id: 'exp_book_s',
      name: '兵法心得',
      description: '武将使用后获得200经验',
      quality: Quality.green,
      type: ItemType.consumable,
      quantity: 3,
    ),
    GameItem(
      id: 'exp_book_m',
      name: '兵法精要',
      description: '武将使用后获得500经验',
      quality: Quality.blue,
      type: ItemType.consumable,
      quantity: 1,
    ),
    // 武器
    GameItem(
      id: 'iron_sword',
      name: '铁剑',
      description: '普通铁制长剑，武力+5',
      quality: Quality.white,
      type: ItemType.weapon,
      quantity: 1,
      attributes: {'force': 5},
    ),
    GameItem(
      id: 'steel_spear',
      name: '钢枪',
      description: '精钢打造的长枪，武力+8',
      quality: Quality.green,
      type: ItemType.weapon,
      quantity: 1,
      attributes: {'force': 8},
    ),
    GameItem(
      id: 'fine_bow',
      name: '良弓',
      description: '弹力十足的良弓，武力+6 速度+3',
      quality: Quality.green,
      type: ItemType.weapon,
      quantity: 1,
      attributes: {'force': 6, 'speed': 3},
    ),
    // 铠甲
    GameItem(
      id: 'wooden_shield',
      name: '木盾',
      description: '简易木制盾牌，统率+3',
      quality: Quality.white,
      type: ItemType.armor,
      quantity: 1,
      attributes: {'command': 3},
    ),
    GameItem(
      id: 'leather_armor',
      name: '皮甲',
      description: '轻便皮甲，统率+5',
      quality: Quality.white,
      type: ItemType.armor,
      quantity: 1,
      attributes: {'command': 5},
    ),
    GameItem(
      id: 'iron_armor',
      name: '铁铠',
      description: '坚固铁铠，统率+10',
      quality: Quality.green,
      type: ItemType.armor,
      quantity: 1,
      attributes: {'command': 10},
    ),
    // 头盔
    GameItem(
      id: 'iron_helmet',
      name: '铁盔',
      description: '铁制头盔，统率+3',
      quality: Quality.white,
      type: ItemType.helmet,
      quantity: 1,
      attributes: {'command': 3},
    ),
    // 坐骑
    GameItem(
      id: 'war_horse',
      name: '战马',
      description: '优良战马，速度+8',
      quality: Quality.green,
      type: ItemType.mount,
      quantity: 1,
      attributes: {'speed': 8},
    ),
    // 兵书
    GameItem(
      id: 'art_of_war',
      name: '孙子兵法',
      description: '兵家必读经典，智力+12',
      quality: Quality.blue,
      type: ItemType.book,
      quantity: 1,
      attributes: {'intelligence': 12},
    ),
    // 宝物
    GameItem(
      id: 'jade_pendant',
      name: '玉佩',
      description: '温润玉佩，魅力+8',
      quality: Quality.green,
      type: ItemType.treasure,
      quantity: 1,
      attributes: {'charm': 8},
    ),
    // 材料
    GameItem(
      id: 'raw_iron',
      name: '生铁',
      description: '锻造装备的基础材料',
      quality: Quality.white,
      type: ItemType.material,
      quantity: 10,
    ),
    GameItem(
      id: 'fine_wood',
      name: '良木',
      description: '建筑升级的上好木材',
      quality: Quality.white,
      type: ItemType.material,
      quantity: 8,
    ),
    GameItem(
      id: 'silk',
      name: '丝绸',
      description: '可用于贸易或赏赐',
      quality: Quality.green,
      type: ItemType.material,
      quantity: 3,
    ),
  ];

  // 根据ID查找技能
  static Skill? findSkill(String skillId) {
    final skills = getAllSkills();
    for (final s in skills) {
      if (s.id == skillId) return s;
    }
    return null;
  }

  // 根据ID查找敌人
  static Enemy? findEnemy(String enemyId) {
    final enemies = getAllEnemies();
    for (final e in enemies) {
      if (e.id == enemyId) return e;
    }
    return null;
  }
}
